L4
zukapa/BaseDjango pull request #4
Opened 2021-06-09 22:58 UTC by zukapa

2021-06-10 07:17 UTC, Vokler requested changes

2021-06-10 07:17 UTC, Vokler commented on users/views.py
> +    return render(request, 'users/register.html', context)
Добавьте сюда еще logout для того, чтобы можно было выходить из системы

2021-06-10 15:29 UTC, zukapa commented on users/views.py
> +    return render(request, 'users/register.html', context)
Изменения внесены в коммите "added logout".

2021-06-11 08:21 UTC, Vokler approved these changes

2021-06-11 08:21 UTC, merged